In [1]:
from analysis import TemperatureDataAnalyzer
file_path = "klementinum.xlsx"
analyzer = TemperatureDataAnalyzer(file_path)
analyzer.read_data()
analyzer.summary_statistics()
print(analyzer.get_data('rok', 'T-AVG').mean())
print(analyzer.get_data('rok', 'TMA').max())
print(analyzer.get_data('rok', 'TMI').min())
print(analyzer.get_data('rok', 'SRA').mean())
analyzer.plot_monthly_avg_temperature()
analyzer.plot_monthly_all_rainfall()
analyzer.plot_yearly_all_temperature(1900, 2020)

A
                rok         měsíc           den         T-AVG           TMA  \
count  90580.000000  90580.000000  90580.000000  90580.000000  90580.000000
mean    1898.500729      6.523029     15.729344      9.764286     13.266869
std       71.591284      3.448695      8.800017      8.333259      9.365293
min     1775.000000      1.000000      1.000000    -24.800000    -21.500000
25%     1836.750000      4.000000      8.000000      3.300000      5.600000
50%     1898.500000      7.000000     16.000000      9.900000     13.500000
75%     1960.250000     10.000000     23.000000     16.700000     21.000000
max     2022.000000     12.000000     31.000000     31.900000     37.800000

                TMI           SRA
count  90580.000000  79837.000000
mean       6.277493      1.292845
std        7.557287      3.636872
min      -27.600000      0.000000
25%        1.000000      0.000000
50%        6.400000      0.000000
75%       12.600000      0.800000
max       24.500000     90.000000
rok
1775    10.748767
1776     8.755464
1777     8.969863
1778    10.231781
1779    10.466301
          ...
2018    12.873425
2019    12.627123
2020    12.307923
2021    11.143014
2022    12.406575
Name: T-AVG, Length: 248, dtype: float64
rok
1775    31.3
1776    32.4
1777    29.3
1778    31.4
1779    29.3
        ...
2018    35.2
2019    37.7
2020    33.5
2021    33.9
2022    36.8
Name: TMA, Length: 248, dtype: float64
rok
1775   -16.0
1776   -22.7
1777   -12.4
1778    -9.9
1779   -13.0
        ...
2018   -11.9
2019    -6.4
2020    -4.9
2021   -11.9
2022    -7.2
Name: TMI, Length: 248, dtype: float64
rok
1804    1.628571
1805    1.182740
1806    1.403892
1807    1.463288
1808    1.201093
          ...
2018    0.996438
2019    1.039726
2020    1.318852
2021    1.359452
2022    1.472603
Name: SRA, Length: 219, dtype: float64